export interface College {
  id: string;
  name: string;
  nickname: string;
  abbreviation: string;
  conference: string;
  primaryColor: string;
  secondaryColor: string;
  jerseyDescription: string;
  primaryHex: string;
  secondaryHex: string;
}

export const COLLEGES: College[] = [
  {
    id: "alabama",
    name: "Alabama",
    nickname: "Crimson Tide",
    abbreviation: "ALA",
    conference: "SEC",
    primaryColor: "crimson red",
    secondaryColor: "white",
    jerseyDescription: "crimson red jersey with white numbers and 'ALABAMA' across the chest, white pants",
    primaryHex: "#9E1B32",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "georgia",
    name: "Georgia",
    nickname: "Bulldogs",
    abbreviation: "UGA",
    conference: "SEC",
    primaryColor: "red",
    secondaryColor: "black",
    jerseyDescription: "red jersey with white numbers and 'GEORGIA' across the chest, white pants with red stripes",
    primaryHex: "#BA0C2F",
    secondaryHex: "#000000",
  },
  {
    id: "ohio-state",
    name: "Ohio State",
    nickname: "Buckeyes",
    abbreviation: "OSU",
    conference: "Big Ten",
    primaryColor: "scarlet red",
    secondaryColor: "gray",
    jerseyDescription: "scarlet red jersey with gray numbers and 'OHIO STATE' across the chest, gray pants",
    primaryHex: "#BB0000",
    secondaryHex: "#A7B1B7",
  },
  {
    id: "michigan",
    name: "Michigan",
    nickname: "Wolverines",
    abbreviation: "MICH",
    conference: "Big Ten",
    primaryColor: "maize yellow",
    secondaryColor: "blue",
    jerseyDescription: "maize yellow jersey with blue numbers and 'MICHIGAN' across the chest, blue pants",
    primaryHex: "#00274C",
    secondaryHex: "#FFCB05",
  },
  {
    id: "penn-state",
    name: "Penn State",
    nickname: "Nittany Lions",
    abbreviation: "PSU",
    conference: "Big Ten",
    primaryColor: "navy blue",
    secondaryColor: "white",
    jerseyDescription: "navy blue jersey with white numbers and 'PENN STATE' across the chest, white pants with navy stripe",
    primaryHex: "#041E42",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "texas",
    name: "Texas",
    nickname: "Longhorns",
    abbreviation: "TEX",
    conference: "SEC",
    primaryColor: "burnt orange",
    secondaryColor: "white",
    jerseyDescription: "burnt orange jersey with white numbers and 'TEXAS' across the chest, white pants",
    primaryHex: "#BF5700",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "notre-dame",
    name: "Notre Dame",
    nickname: "Fighting Irish",
    abbreviation: "ND",
    conference: "Independent",
    primaryColor: "navy blue",
    secondaryColor: "gold",
    jerseyDescription: "navy blue jersey with gold numbers and 'NOTRE DAME' across the chest, gold pants",
    primaryHex: "#0C2340",
    secondaryHex: "#C99700",
  },
  {
    id: "clemson",
    name: "Clemson",
    nickname: "Tigers",
    abbreviation: "CLEM",
    conference: "ACC",
    primaryColor: "orange",
    secondaryColor: "purple",
    jerseyDescription: "orange jersey with purple numbers and 'CLEMSON' across the chest, white pants with orange stripe",
    primaryHex: "#F66733",
    secondaryHex: "#522D80",
  },
  {
    id: "lsu",
    name: "LSU",
    nickname: "Tigers",
    abbreviation: "LSU",
    conference: "SEC",
    primaryColor: "purple",
    secondaryColor: "gold",
    jerseyDescription: "purple jersey with gold numbers and 'LSU' across the chest, white pants with purple and gold stripes",
    primaryHex: "#461D7C",
    secondaryHex: "#FDD023",
  },
  {
    id: "florida",
    name: "Florida",
    nickname: "Gators",
    abbreviation: "FLA",
    conference: "SEC",
    primaryColor: "royal blue",
    secondaryColor: "orange",
    jerseyDescription: "royal blue jersey with orange numbers and 'FLORIDA' across the chest, white pants",
    primaryHex: "#0021A5",
    secondaryHex: "#FA4616",
  },
  {
    id: "tennessee",
    name: "Tennessee",
    nickname: "Volunteers",
    abbreviation: "TENN",
    conference: "SEC",
    primaryColor: "Tennessee orange",
    secondaryColor: "white",
    jerseyDescription: "bright Tennessee orange jersey with white numbers and 'TENNESSEE' across the chest, white pants",
    primaryHex: "#FF8200",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "oregon",
    name: "Oregon",
    nickname: "Ducks",
    abbreviation: "ORE",
    conference: "Big Ten",
    primaryColor: "green",
    secondaryColor: "yellow",
    jerseyDescription: "dark green jersey with yellow numbers and 'OREGON' across the chest, white pants",
    primaryHex: "#154733",
    secondaryHex: "#FEE123",
  },
  {
    id: "miami",
    name: "Miami",
    nickname: "Hurricanes",
    abbreviation: "MIA",
    conference: "ACC",
    primaryColor: "orange",
    secondaryColor: "green",
    jerseyDescription: "white jersey with orange and green numbers and 'MIAMI' across the chest, white pants with orange and green stripes",
    primaryHex: "#F47321",
    secondaryHex: "#005030",
  },
  {
    id: "usc",
    name: "USC",
    nickname: "Trojans",
    abbreviation: "USC",
    conference: "Big Ten",
    primaryColor: "cardinal red",
    secondaryColor: "gold",
    jerseyDescription: "cardinal red jersey with gold numbers and 'USC' across the chest, white pants",
    primaryHex: "#990000",
    secondaryHex: "#FFC72C",
  },
  {
    id: "oklahoma",
    name: "Oklahoma",
    nickname: "Sooners",
    abbreviation: "OU",
    conference: "SEC",
    primaryColor: "crimson",
    secondaryColor: "cream",
    jerseyDescription: "crimson jersey with cream numbers and 'OKLAHOMA' across the chest, white pants",
    primaryHex: "#841617",
    secondaryHex: "#F5F0DB",
  },
  {
    id: "texas-am",
    name: "Texas A&M",
    nickname: "Aggies",
    abbreviation: "TAMU",
    conference: "SEC",
    primaryColor: "maroon",
    secondaryColor: "white",
    jerseyDescription: "maroon jersey with white numbers and 'TEXAS A&M' across the chest, white pants",
    primaryHex: "#500000",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "auburn",
    name: "Auburn",
    nickname: "Tigers",
    abbreviation: "AUB",
    conference: "SEC",
    primaryColor: "navy blue",
    secondaryColor: "orange",
    jerseyDescription: "navy blue jersey with orange numbers and 'AUBURN' across the chest, white pants with orange and blue stripes",
    primaryHex: "#03244D",
    secondaryHex: "#E87722",
  },
  {
    id: "florida-state",
    name: "Florida State",
    nickname: "Seminoles",
    abbreviation: "FSU",
    conference: "ACC",
    primaryColor: "garnet",
    secondaryColor: "gold",
    jerseyDescription: "garnet jersey with gold numbers and 'FLORIDA STATE' across the chest, white pants",
    primaryHex: "#782F40",
    secondaryHex: "#CEB888",
  },
  {
    id: "north-carolina",
    name: "North Carolina",
    nickname: "Tar Heels",
    abbreviation: "UNC",
    conference: "ACC",
    primaryColor: "Carolina blue",
    secondaryColor: "white",
    jerseyDescription: "Carolina blue jersey with white numbers and 'CAROLINA' across the chest, white pants",
    primaryHex: "#4B9CD3",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "washington",
    name: "Washington",
    nickname: "Huskies",
    abbreviation: "WASH",
    conference: "Big Ten",
    primaryColor: "purple",
    secondaryColor: "gold",
    jerseyDescription: "purple jersey with gold numbers and 'WASHINGTON' across the chest, white pants",
    primaryHex: "#33006F",
    secondaryHex: "#E8A900",
  },
  {
    id: "wisconsin",
    name: "Wisconsin",
    nickname: "Badgers",
    abbreviation: "WIS",
    conference: "Big Ten",
    primaryColor: "cardinal red",
    secondaryColor: "white",
    jerseyDescription: "cardinal red jersey with white numbers and 'WISCONSIN' across the chest, white pants with red stripe",
    primaryHex: "#C5050C",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "nebraska",
    name: "Nebraska",
    nickname: "Cornhuskers",
    abbreviation: "NEB",
    conference: "Big Ten",
    primaryColor: "scarlet red",
    secondaryColor: "cream",
    jerseyDescription: "scarlet red jersey with cream numbers and 'NEBRASKA' across the chest, white pants",
    primaryHex: "#E41C38",
    secondaryHex: "#F5F1E7",
  },
  {
    id: "iowa",
    name: "Iowa",
    nickname: "Hawkeyes",
    abbreviation: "IOWA",
    conference: "Big Ten",
    primaryColor: "black",
    secondaryColor: "gold",
    jerseyDescription: "black jersey with gold numbers and 'IOWA' across the chest, black pants with gold stripe",
    primaryHex: "#FFCD00",
    secondaryHex: "#000000",
  },
  {
    id: "minnesota",
    name: "Minnesota",
    nickname: "Golden Gophers",
    abbreviation: "MINN",
    conference: "Big Ten",
    primaryColor: "maroon",
    secondaryColor: "gold",
    jerseyDescription: "maroon jersey with gold numbers and 'MINNESOTA' across the chest, gold pants",
    primaryHex: "#7A0019",
    secondaryHex: "#FFCC33",
  },
  {
    id: "arkansas",
    name: "Arkansas",
    nickname: "Razorbacks",
    abbreviation: "ARK",
    conference: "SEC",
    primaryColor: "cardinal red",
    secondaryColor: "white",
    jerseyDescription: "cardinal red jersey with white numbers and 'ARKANSAS' across the chest, white pants",
    primaryHex: "#9D2235",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "ole-miss",
    name: "Ole Miss",
    nickname: "Rebels",
    abbreviation: "MISS",
    conference: "SEC",
    primaryColor: "powder blue",
    secondaryColor: "red",
    jerseyDescription: "powder blue jersey with red and white numbers and 'OLE MISS' across the chest, white pants",
    primaryHex: "#14213D",
    secondaryHex: "#CE1126",
  },
  {
    id: "mississippi-state",
    name: "Mississippi State",
    nickname: "Bulldogs",
    abbreviation: "MSST",
    conference: "SEC",
    primaryColor: "maroon",
    secondaryColor: "white",
    jerseyDescription: "maroon jersey with white numbers and 'MISSISSIPPI STATE' across the chest, white pants",
    primaryHex: "#660000",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "kentucky",
    name: "Kentucky",
    nickname: "Wildcats",
    abbreviation: "UK",
    conference: "SEC",
    primaryColor: "royal blue",
    secondaryColor: "white",
    jerseyDescription: "royal blue jersey with white numbers and 'KENTUCKY' across the chest, white pants",
    primaryHex: "#0033A0",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt",
    nickname: "Commodores",
    abbreviation: "VAN",
    conference: "SEC",
    primaryColor: "black",
    secondaryColor: "gold",
    jerseyDescription: "black jersey with gold numbers and 'VANDERBILT' across the chest, black pants",
    primaryHex: "#000000",
    secondaryHex: "#CFAE70",
  },
  {
    id: "south-carolina",
    name: "South Carolina",
    nickname: "Gamecocks",
    abbreviation: "SC",
    conference: "SEC",
    primaryColor: "garnet",
    secondaryColor: "black",
    jerseyDescription: "garnet jersey with black numbers and 'SOUTH CAROLINA' across the chest, black pants",
    primaryHex: "#73000A",
    secondaryHex: "#000000",
  },
  {
    id: "missouri",
    name: "Missouri",
    nickname: "Tigers",
    abbreviation: "MIZ",
    conference: "SEC",
    primaryColor: "black",
    secondaryColor: "gold",
    jerseyDescription: "black jersey with gold numbers and 'MISSOURI' across the chest, black pants with gold stripe",
    primaryHex: "#F1B82D",
    secondaryHex: "#000000",
  },
  {
    id: "michigan-state",
    name: "Michigan State",
    nickname: "Spartans",
    abbreviation: "MSU",
    conference: "Big Ten",
    primaryColor: "dark green",
    secondaryColor: "white",
    jerseyDescription: "dark green jersey with white numbers and 'MICHIGAN STATE' across the chest, white pants with green stripe",
    primaryHex: "#18453B",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "purdue",
    name: "Purdue",
    nickname: "Boilermakers",
    abbreviation: "PUR",
    conference: "Big Ten",
    primaryColor: "black",
    secondaryColor: "gold",
    jerseyDescription: "black jersey with gold numbers and 'PURDUE' across the chest, black pants with gold stripe",
    primaryHex: "#CEB888",
    secondaryHex: "#000000",
  },
  {
    id: "indiana",
    name: "Indiana",
    nickname: "Hoosiers",
    abbreviation: "IND",
    conference: "Big Ten",
    primaryColor: "crimson",
    secondaryColor: "cream",
    jerseyDescription: "crimson jersey with cream numbers and 'INDIANA' across the chest, white pants with crimson stripe",
    primaryHex: "#990000",
    secondaryHex: "#F2E4C3",
  },
  {
    id: "rutgers",
    name: "Rutgers",
    nickname: "Scarlet Knights",
    abbreviation: "RUT",
    conference: "Big Ten",
    primaryColor: "scarlet red",
    secondaryColor: "white",
    jerseyDescription: "scarlet red jersey with white numbers and 'RUTGERS' across the chest, white pants",
    primaryHex: "#CC0033",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "maryland",
    name: "Maryland",
    nickname: "Terrapins",
    abbreviation: "MD",
    conference: "Big Ten",
    primaryColor: "red",
    secondaryColor: "gold",
    jerseyDescription: "red jersey with gold numbers and 'MARYLAND' across the chest, white pants with red and gold stripes",
    primaryHex: "#E03A3E",
    secondaryHex: "#FFD520",
  },
  {
    id: "colorado",
    name: "Colorado",
    nickname: "Buffaloes",
    abbreviation: "COL",
    conference: "Big 12",
    primaryColor: "black",
    secondaryColor: "gold",
    jerseyDescription: "black jersey with gold numbers and 'COLORADO' across the chest, black pants with gold stripe",
    primaryHex: "#000000",
    secondaryHex: "#CFB87C",
  },
  {
    id: "utah",
    name: "Utah",
    nickname: "Utes",
    abbreviation: "UTAH",
    conference: "Big 12",
    primaryColor: "crimson red",
    secondaryColor: "white",
    jerseyDescription: "crimson red jersey with white numbers and 'UTAH' across the chest, white pants",
    primaryHex: "#CC0000",
    secondaryHex: "#000000",
  },
  {
    id: "byu",
    name: "BYU",
    nickname: "Cougars",
    abbreviation: "BYU",
    conference: "Big 12",
    primaryColor: "navy blue",
    secondaryColor: "white",
    jerseyDescription: "navy blue jersey with white numbers and 'BYU' across the chest, white pants with navy stripe",
    primaryHex: "#002255",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "kansas-state",
    name: "Kansas State",
    nickname: "Wildcats",
    abbreviation: "KSU",
    conference: "Big 12",
    primaryColor: "purple",
    secondaryColor: "silver",
    jerseyDescription: "purple jersey with silver numbers and 'KANSAS STATE' across the chest, white pants",
    primaryHex: "#512888",
    secondaryHex: "#D1D1D1",
  },
  {
    id: "oklahoma-state",
    name: "Oklahoma State",
    nickname: "Cowboys",
    abbreviation: "OKST",
    conference: "Big 12",
    primaryColor: "orange",
    secondaryColor: "black",
    jerseyDescription: "orange jersey with black numbers and 'OKLAHOMA STATE' across the chest, black pants with orange stripe",
    primaryHex: "#FF6600",
    secondaryHex: "#000000",
  },
  {
    id: "tcu",
    name: "TCU",
    nickname: "Horned Frogs",
    abbreviation: "TCU",
    conference: "Big 12",
    primaryColor: "purple",
    secondaryColor: "white",
    jerseyDescription: "purple jersey with white numbers and 'TCU' across the chest, white pants with purple stripe",
    primaryHex: "#4D1979",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "baylor",
    name: "Baylor",
    nickname: "Bears",
    abbreviation: "BAY",
    conference: "Big 12",
    primaryColor: "green",
    secondaryColor: "gold",
    jerseyDescription: "green jersey with gold numbers and 'BAYLOR' across the chest, gold pants",
    primaryHex: "#154734",
    secondaryHex: "#FFB81C",
  },
  {
    id: "iowa-state",
    name: "Iowa State",
    nickname: "Cyclones",
    abbreviation: "ISU",
    conference: "Big 12",
    primaryColor: "cardinal red",
    secondaryColor: "gold",
    jerseyDescription: "cardinal red jersey with gold numbers and 'IOWA STATE' across the chest, white pants with red and gold stripes",
    primaryHex: "#C8102E",
    secondaryHex: "#F1BE48",
  },
  {
    id: "west-virginia",
    name: "West Virginia",
    nickname: "Mountaineers",
    abbreviation: "WVU",
    conference: "Big 12",
    primaryColor: "navy blue",
    secondaryColor: "gold",
    jerseyDescription: "navy blue jersey with gold numbers and 'WEST VIRGINIA' across the chest, gold pants",
    primaryHex: "#002855",
    secondaryHex: "#EAAA00",
  },
  {
    id: "kansas",
    name: "Kansas",
    nickname: "Jayhawks",
    abbreviation: "KU",
    conference: "Big 12",
    primaryColor: "royal blue",
    secondaryColor: "red",
    jerseyDescription: "royal blue jersey with red numbers and 'KANSAS' across the chest, white pants with blue and red stripes",
    primaryHex: "#0051A5",
    secondaryHex: "#E8000D",
  },
  {
    id: "virginia-tech",
    name: "Virginia Tech",
    nickname: "Hokies",
    abbreviation: "VT",
    conference: "ACC",
    primaryColor: "maroon",
    secondaryColor: "orange",
    jerseyDescription: "maroon jersey with orange numbers and 'VIRGINIA TECH' across the chest, white pants with maroon and orange stripes",
    primaryHex: "#861F41",
    secondaryHex: "#CF4420",
  },
  {
    id: "nc-state",
    name: "NC State",
    nickname: "Wolfpack",
    abbreviation: "NCST",
    conference: "ACC",
    primaryColor: "red",
    secondaryColor: "white",
    jerseyDescription: "red jersey with white numbers and 'NC STATE' across the chest, white pants with red stripe",
    primaryHex: "#CC0000",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "pittsburgh",
    name: "Pittsburgh",
    nickname: "Panthers",
    abbreviation: "PITT",
    conference: "ACC",
    primaryColor: "royal blue",
    secondaryColor: "gold",
    jerseyDescription: "royal blue jersey with gold numbers and 'PITT' across the chest, gold pants",
    primaryHex: "#003594",
    secondaryHex: "#FFB81C",
  },
  {
    id: "wake-forest",
    name: "Wake Forest",
    nickname: "Demon Deacons",
    abbreviation: "WAKE",
    conference: "ACC",
    primaryColor: "black",
    secondaryColor: "old gold",
    jerseyDescription: "black jersey with old gold numbers and 'WAKE FOREST' across the chest, black pants with gold stripe",
    primaryHex: "#000000",
    secondaryHex: "#9E7E38",
  },
  {
    id: "syracuse",
    name: "Syracuse",
    nickname: "Orange",
    abbreviation: "SYR",
    conference: "ACC",
    primaryColor: "orange",
    secondaryColor: "blue",
    jerseyDescription: "orange jersey with blue numbers and 'SYRACUSE' across the chest, white pants with orange stripe",
    primaryHex: "#F76900",
    secondaryHex: "#003A98",
  },
  {
    id: "boston-college",
    name: "Boston College",
    nickname: "Eagles",
    abbreviation: "BC",
    conference: "ACC",
    primaryColor: "maroon",
    secondaryColor: "gold",
    jerseyDescription: "maroon jersey with gold numbers and 'BOSTON COLLEGE' across the chest, white pants",
    primaryHex: "#98002E",
    secondaryHex: "#BC9B6A",
  },
  {
    id: "duke",
    name: "Duke",
    nickname: "Blue Devils",
    abbreviation: "DUKE",
    conference: "ACC",
    primaryColor: "royal blue",
    secondaryColor: "white",
    jerseyDescription: "royal blue jersey with white numbers and 'DUKE' across the chest, white pants",
    primaryHex: "#003087",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "georgia-tech",
    name: "Georgia Tech",
    nickname: "Yellow Jackets",
    abbreviation: "GT",
    conference: "ACC",
    primaryColor: "navy blue",
    secondaryColor: "gold",
    jerseyDescription: "navy blue jersey with gold numbers and 'GEORGIA TECH' across the chest, gold pants",
    primaryHex: "#B3A369",
    secondaryHex: "#003057",
  },
  {
    id: "louisville",
    name: "Louisville",
    nickname: "Cardinals",
    abbreviation: "LOU",
    conference: "ACC",
    primaryColor: "cardinal red",
    secondaryColor: "black",
    jerseyDescription: "cardinal red jersey with black numbers and 'LOUISVILLE' across the chest, black pants with red stripe",
    primaryHex: "#AD0000",
    secondaryHex: "#000000",
  },
  {
    id: "california",
    name: "California",
    nickname: "Golden Bears",
    abbreviation: "CAL",
    conference: "ACC",
    primaryColor: "navy blue",
    secondaryColor: "gold",
    jerseyDescription: "navy blue jersey with gold numbers and 'CALIFORNIA' across the chest, gold pants",
    primaryHex: "#003262",
    secondaryHex: "#FDB515",
  },
  {
    id: "stanford",
    name: "Stanford",
    nickname: "Cardinal",
    abbreviation: "STAN",
    conference: "ACC",
    primaryColor: "cardinal red",
    secondaryColor: "white",
    jerseyDescription: "cardinal red jersey with white numbers and 'STANFORD' across the chest, white pants",
    primaryHex: "#8C1515",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "smu",
    name: "SMU",
    nickname: "Mustangs",
    abbreviation: "SMU",
    conference: "ACC",
    primaryColor: "royal blue",
    secondaryColor: "red",
    jerseyDescription: "royal blue jersey with red numbers and 'SMU' across the chest, white pants",
    primaryHex: "#003594",
    secondaryHex: "#CC0000",
  },

  // ── Big Ten additions ──────────────────────────────────────────────────────
  {
    id: "illinois",
    name: "Illinois",
    nickname: "Fighting Illini",
    abbreviation: "ILL",
    conference: "Big Ten",
    primaryColor: "navy blue",
    secondaryColor: "orange",
    jerseyDescription: "navy blue jersey with orange numbers and 'ILLINOIS' across the chest, white pants with orange and navy stripes",
    primaryHex: "#E84A27",
    secondaryHex: "#13294B",
  },
  {
    id: "northwestern",
    name: "Northwestern",
    nickname: "Wildcats",
    abbreviation: "NW",
    conference: "Big Ten",
    primaryColor: "purple",
    secondaryColor: "white",
    jerseyDescription: "purple jersey with white numbers and 'NORTHWESTERN' across the chest, white pants with purple stripe",
    primaryHex: "#4E2A84",
    secondaryHex: "#FFFFFF",
  },

  // ── Big 12 additions ───────────────────────────────────────────────────────
  {
    id: "arizona",
    name: "Arizona",
    nickname: "Wildcats",
    abbreviation: "ARIZ",
    conference: "Big 12",
    primaryColor: "cardinal red",
    secondaryColor: "navy blue",
    jerseyDescription: "cardinal red jersey with navy blue numbers and 'ARIZONA' across the chest, white pants",
    primaryHex: "#CC0033",
    secondaryHex: "#0C234B",
  },
  {
    id: "arizona-state",
    name: "Arizona State",
    nickname: "Sun Devils",
    abbreviation: "ASU",
    conference: "Big 12",
    primaryColor: "maroon",
    secondaryColor: "gold",
    jerseyDescription: "maroon jersey with gold numbers and 'ARIZONA STATE' across the chest, white pants with maroon and gold stripes",
    primaryHex: "#8C1D40",
    secondaryHex: "#FFC627",
  },
  {
    id: "cincinnati",
    name: "Cincinnati",
    nickname: "Bearcats",
    abbreviation: "CIN",
    conference: "Big 12",
    primaryColor: "red",
    secondaryColor: "black",
    jerseyDescription: "red jersey with black numbers and 'CINCINNATI' across the chest, black pants with red stripe",
    primaryHex: "#E00122",
    secondaryHex: "#000000",
  },
  {
    id: "houston",
    name: "Houston",
    nickname: "Cougars",
    abbreviation: "HOU",
    conference: "Big 12",
    primaryColor: "scarlet red",
    secondaryColor: "white",
    jerseyDescription: "scarlet red jersey with white numbers and 'HOUSTON' across the chest, white pants with red stripe",
    primaryHex: "#C8102E",
    secondaryHex: "#FFFFFF",
  },
  {
    id: "texas-tech",
    name: "Texas Tech",
    nickname: "Red Raiders",
    abbreviation: "TTU",
    conference: "Big 12",
    primaryColor: "red",
    secondaryColor: "black",
    jerseyDescription: "red jersey with black numbers and 'TEXAS TECH' across the chest, white pants with red and black stripes",
    primaryHex: "#CC0000",
    secondaryHex: "#000000",
  },
  {
    id: "ucf",
    name: "UCF",
    nickname: "Knights",
    abbreviation: "UCF",
    conference: "Big 12",
    primaryColor: "black",
    secondaryColor: "gold",
    jerseyDescription: "black jersey with gold numbers and 'UCF' across the chest, black pants with gold stripe",
    primaryHex: "#B6862C",
    secondaryHex: "#000000",
  },

  // ── ACC additions ──────────────────────────────────────────────────────────
  {
    id: "virginia",
    name: "Virginia",
    nickname: "Cavaliers",
    abbreviation: "UVA",
    conference: "ACC",
    primaryColor: "navy blue",
    secondaryColor: "orange",
    jerseyDescription: "navy blue jersey with orange numbers and 'VIRGINIA' across the chest, white pants with navy and orange stripes",
    primaryHex: "#232D4B",
    secondaryHex: "#E57200",
  },
];

export const CONFERENCES = [
  "All",
  "SEC",
  "Big Ten",
  "Big 12",
  "ACC",
  "Independent",
];

export function getCollegesByConference(conference: string): College[] {
  if (conference === "All") return COLLEGES;
  return COLLEGES.filter((c) => c.conference === conference);
}
